### PR TITLE
Improve Makefile portability

### PR DESCRIPTION
**Pull request by deuxksix**
Rework part of the `Makefile` in order to make it more portable:
- support platforms where `/bin/dash` is used as POSIX shell
  - replace `&>` by `2>&1`
  - replace `source <file>` by `. <file>`
  - replace `echo -e '\n ...'` by `echo; echo '...'`
  - replace `declare -u var=$var` by `var=$(echo $var | tr '[:lower:]' '[:upper:]')`
- support platforms where `python3` is not the default
  - replace `python` by `/usr/bin/env python3`
  - replace `pip install` by `/usr/bin/env python3 -m pip`
 
There is also a new `has-board-installed` target to checks for missing board installation:
```
ERROR: board "adafruit:nrf52:lampDa_nrf52840" not found!

Troubleshooting:
 - home directory is "/home/$USER"
 - detected arduino data directory is "/home/$USER/.arduino15"
 - adafruit should be listed in "/home/$USER/.arduino15/packages" below:
        adafruit  arduino  builtin
 - nrf52 should be listed in "/home/$USER/.arduino15/packages/hardware" below:
        nrf52
 - have you replaced it by the "custom LampDa platform" repository?
 - if yes, the "LampDa_nrf52840" board should be listed below:

cplaynrf52840.build.variant=circuitplayground_nrf52840
cluenrf52840.build.variant=clue_nrf52840
ledglasses_nrf52840.build.variant=ledglasses_nrf52840
```

And new `has-libs-installed` targets to checks for missing library dependencies:
```
ERROR: library "Adafruit NeoPixel" not found!

Troubleshooting:
 - home directory is "/home/$USER"
 - detected arduino user directory is "/home/$USER/Arduino"
 - library should be listed in "/home/$USER/Arduino/libraries" below:
        ArduinoFFT
 - install it through the IDE or using the following:
        arduino-cli lib install "Adafruit NeoPixel"
```

I haven't tested this on a real Ubuntu setup (for example) but it should help!

### CODE REVIEW

**Comment by deuxksix** [comment]
Added `wheel` in `requirements.txt` for platforms that needs it for `adafruit-nrfutil`

Also improves build log readability by filtering `Using cached` and `Using previously compiled` messages

**Comment by deuxksix** [comment]
Detect `$(COMPILER_CMD)` and `$(COMPILER_PATH)` instead of hard-coding these values

**Comment by deuxksix** [comment]
Check that `$(COMPILER_PATH)$(COMPILER_CMD)` is a working `Arm Embedded Processors` compiler

**Comment by deuxksix** [comment]
Added `make unsafe-board-install` and `make unsafe-install-libs` to help users fix a broken `arduino-cli` install

**Note:** as a caveat, doing such modifications through the command line may break local IDE install :/

**Comment by deuxksix** [comment]
Added a `make safe-install` target that install all dependencies in a separate `_build/arduino-cli` directory

This can help user that has trouble installing a working environment (while taking up to ~1.4 gigabytes of disk space)

**Comment by deuxksix** [comment]
Update recommendation to use `make mr_proper safe-install` for broken installs

Explicitly add `$(VENV_DIR)/bin` to `$PATH` in `tools/arduino-cli` to support some plaforms with bad `virtualenv` support

**Comment by deuxksix** [comment]
Added a check that `adafruit-nrfutil` is available in python3 virtual environment

Adds the following error message -- here triggered on a working setup:
```
ERROR: python3 virtualenv seems to be not be functioning?

Troubleshooting:
 - virtualenv created at "/home/plcp/plabs/lampda/git/lampda1/LampColorControler/venv"
 - "source /home/plcp/plabs/lampda/git/lampda1/LampColorControler/venv/bin/activate" should make adafruit-nrfutil available in $PATH
 - packages like "python3-pip", "python3-venv" or "python3-wheel" may be needed locally
 - try "python3 -m pip install --user adafruit-nrfutil" to attempt to use local install
 - expected "adafruit-nrfutil version" literal string in the following command output:

 $ . /home/plcp/plabs/lampda/git/lampda1/LampColorControler/venv/bin/activate && adafruit-nrfutil version
adafruit-nrfutil version 0.5.3.post16
```

**Comment by deuxksix** [comment]
Give up on `/bin/dash` support and defaults to using `/bin/bash` as a last attempt to fix problems related to `virtualenv`

**Comment by deuxksix** [comment]
Another attempt to help troubleshooting with an error message if `LampColorController.ino.hex` exists but not `LampColorController.ino.zip`:

```
ERROR: looks like "adafruit-nrfutil dfu genpkg" command failed to run?

Troubleshooting:
 - check in arduino logs that "adafruit-nrfutil" command was found in $PATH
 - if not, verify that "adafruit-nrfutil" is installed in "$(VENV_DIR)"
 - if not, try the following to force a local install of the package:
        python3 -m pip install --break-system-packages --user adafruit-nrfutil
 - you can also try to run by hand the following:
        adafruit-nrfutil dfu genpkg --dev-type 0x0052 --sd-req 0x0123 --application $(BUILD_DIR)/objs/LampColorControler.ino.hex $(BUILD_DIR)/objs/LampColorControler.ino.zip
```

**Comment by deuxksix** [comment]
Now will properly display error message if user haven't installed `python3-venv`

**Comment by deuxksix** [comment]
Fix missing `install-venv` dependency and fix `/bin/dash` compatibility (again)

**Comment by deuxksix** [comment]
Propose to Linux 64-bit users to install `arduino-cli` for them in the local directory

**Comment by deuxksix** [comment]
Warn against broken `arduino-cli` install

**Comment by BaptisteHudyma** [comment]
Thanks for the  great work !

**Pull request merged**
